setup.py
Helps out with Issue #9.
Currently, you need PIP v1.2 or higher.
This adds support for PIP v1.1 _(Which is what is in the Debian 7.x repo currently)._
```bash
root@kali /usr/share/wafw00f_git$ pip --version
pip 1.1 from /usr/lib/python2.7/dist-packages (python 2.7)
root@kali /usr/share/wafw00f_git$ python setup.py install                                                                                                         master 
Traceback (most recent call last):
File "setup.py", line 24, in <module>
install_requires=get_reqs(),
File "setup.py", line 10, in get_reqs
return [str(ir.req) for ir in install_reqs]
File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1240, in parse_requirements
skip_regex = options.skip_requirements_regex
AttributeError: 'NoneType' object has no …
```
=> PIP v1.1 support (For Issue #9)

wafw00f/plugins/f5bigipasm.py
[This page](https://support.f5.com/kb/en-us/solutions/public/6000/800/sol6850.html)
on F5's site has some new details on how ASM boxes set cookies, basically:
> - In BIG-IP ASM 11.3.0 and later:  (TSxxxxxxxx) The Main ASM cookie name structure contains eight hexadecimal characters.
> - In BIG-IP ASM 10.x - 11.2.1: (TSxxxxxx) The cookie contains six characters that are a hexadecimal representation of the httpclass name that holds the active security policy.
This means that you can use the length of the cookie to do basic version
detection (although I don't think waf200f currently support this).
This commit allows up to 8 hex chars in the TS cookie. 
There are also some other cookies mentioned in the docs, but I've not seen them in the wild.
=> Newer F5 BIG-IP ASM releases use 8 char cookies

wafw00f/main.py, wafw00f/plugins/nsfocus.py
This plugin detects NSFocus.
Homepage:
* http://nsfocusglobal.com/
I've tested this plugin on a simple HTTP server with spoofed `server` header. I haven't tested this plugin on the WAF as I don't have a test WAF upon which to test.
Implemented based on:
* https://github.com/urbanadventurer/WhatWeb/tree/master/plugins/NSFocus.rb
```
root@kali:/pentest/web/wafw00f# wafw00f http://127.0.0.1:8080/ 
^     ^
_   __  _   ____ _   __  _    _   ____
///7/ /.' \ / __////7/ /,' \ ,' \ / __/
| V V // o // _/ | V V // 0 // 0 // _/
|_n_,'/_n_//_/   |_n_,' \_,' \_,'/_/
<
...'
WAFW00F - Web Application Firewall Detection Tool
By Sandro Gauci && Wendel G. Henrique
Checking http://127.0.0.1:8080/
The site http://127.0.0.1:8080/ is behind a Imperva SecureSphere
Number of requests: 8
```
``` …
```
=> add plugin: NSFocus

wafw00f/main.py, wafw00f/plugins/missioncontrol.py
This plugin detects Mission Control Application Shield (part of Mission Control Security Services by Open Systems AG).
Homepage:
* https://web.archive.org/web/20120512065505/http://open.ch/1_1_2_1.html
* https://web.archive.org/web/20120510030448/http://www.open.ch/missioncontrol.html
I've tested this plugin on a simple HTTP server with spoofed `server` header. I haven't tested this plugin on the WAF as I don't have a test WAF upon which to test.
Implemented based on:
* https://github.com/urbanadventurer/WhatWeb/tree/master/plugins/Mission-Control-Application-Shield.rb
```
root@kali:/pentest/web/wafw00f# wafw00f http://127.0.0.1:8080/ 
^     ^
_   __  _   ____ _   __  _    _   ____
///7/ /.' \ / __////7/ /,' \ ,' \ / __/
| V V // o // _/ | V V // 0 // 0 // _/
|_n_,'/_n_//_/   |_n_,' \_,' …
```
=> add plugin: Mission Control Application Shield

wafw00f/main.py, wafw00f/plugins/safedog.py
This plugin detects Safedog.
* Homepage: http://safedog.cn/
I've tested this plugin on a simple HTTP server with spoofed `server`, `x-powered-by` and `set-cookie` headers. I haven't tested this plugin on the WAF as I don't have a test WAF upon which to test.
```
./wafw00f/bin/wafw00f 127.0.0.1:8080 
^     ^
_   __  _   ____ _   __  _    _   ____
///7/ /.' \ / __////7/ /,' \ ,' \ / __/
| V V // o // _/ | V V // 0 // 0 // _/
|_n_,'/_n_//_/   |_n_,' \_,' \_,'/_/
<
...'
WAFW00F - Web Application Firewall Detection Tool
By Sandro Gauci && Wendel G. Henrique
Checking http://127.0.0.1:8080
The site http://127.0.0.1:8080 is behind a Safedog
Number of requests: 1
```
=> add plugin: Safedog

setup.py, wafw00f/lib/evillib.py, wafw00f/lib/proxy.py, wafw00f/main.py
Optionally allow to specify an http or socks5 proxy.
* -p http://hostname:8080
* -p socks5://hostname:1080
Some minor changes were made to improve python3.5 compatibility.
=> Add support for HTTP and socks5 proxies

wafw00f/main.py, wafw00f/plugins/modsecuritycrs.py
Mod security with basic rules was not being detected. Generic detection missed it too. This plugin checks for a variation when the attack is in arbitrary query argument.
Additionally, I slightly altered the checking logic so plugins not hardcoded in main.py also get executed.
=> Add mod_security plugin with OWASP CRS base rules

wafw00f/plugins/betterwpsecurity.py
This wordpress plugin can be ban users scanning sites.
The check performs an additional request only if the site appears to be a wordpress site.
=> Detect presence of better-wp-security

wafw00f/plugins/betterwpsecurity.py, wafw00f/plugins/modsecuritycrs.py
My previous contributions omitted to include self.path as part of the base path, which caused false positives in some cases for modsec, and failures to detect for betterwpsec.
=> Make sure base path is respected for modsec and betterwpsec plugins

wafw00f/lib/evillib.py
Fix for #28 broke socks5 proxy support.
=> This exception is only valid for http proxy, not socks5

wafw00f/plugins/betterwpsecurity.py, wafw00f/plugins/ibm.py
All plugins were reviewed. This one (mine) was the only one with the issue.
Additionally, check the normal response in IBM plugin as it yields false
positives when the site does not respond. The reason came clear upon review.
=> Check responses in better-wp-security to avoid NoneType exception

docs/wafw00f.8
Hello, this was a manpage that we've written while packaging wafw00f for Debian, it is based (almost exactly) as wafw00f's help output, but it's still better than nothing :)
=> Add manpage

setup.py
Remove the pinning of dependencies to make `wafw00f` installable beside other tools, e.g., in a `venv`. This is also required if the tool is shipped as package (e.g., [Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1704958) already has later releases of the dependencies as package available).
=> Remove release pinning

README.md, wafw00f/plugins/cloudbric.py, wafw00f/wafprio.py
I just noticed that some bugs had somehow crept in within the Cloudbric fingerprint plugin. Also I extensively tested the Cloudbric plugin against 7+ sites which yielded another new variant of the WAF blockpage. Our two principle attack vectors within wafw00f, yeilds:
- `../../../etc/passwd` yeilds:
- `<script>alert()</script>` yeilds:
More accurate detection. ;)
=> Fixed some bugs + More Cloudbric Fingerprints

wafw00f/plugins/xlabssecuritywaf.py
During testing of the XLabs Security plugin on 3 sites, I found another header fingerprint which is quite reliable in fingerprinting XLabs WAF.
```
Secured: By XLabs Security www.xlabs.com.br
Server: Apache
Strict-Transport-Security: max-age=63072000; preload
Vary: Accept-Encoding
x-cdn: XLabs Security
X-CDN-Request-ID: XOADaH8AAAEAAGqzWK8AAAAW
X-UA-Compatible: IE=Edge,chrome=1
```
Also I noticed that the existing `Server` based fingerprint is reproduced only during attack conditions. 
```
Connection: Keep-Alive
Content-Length: 241
Content-Type: text/html; charset=iso-8859-1
Date: Sat, 18 May 2019 13:14:49 GMT
Keep-Alive: timeout=5, max=100
Public-Key-Pins: pin-sha256="4U/WhYNLrhkKLLrXPtJOAPEXFhzqq8YGNbQAy50Vy74="; pin-sha256="HxT9JlwH08GBgejrE3cqgoT6MdFvjeSalyXv2+sFnbg="; max-age=300 …
```
=> New header fingerprint + Fixing fingerprint for XLabs WAF

wafw00f/plugins/ptaf.py
Fix error in Request ID regex that breaks correct WAF identification.
Changed 15 to 35, because 15 symbols between date and 'pre>' are not enough for this signature.
Sample of WAF block response:
```
<h1>Forbidden</h1><pre>Request ID: 2017-07-31-13-59-56-72BCA33A11EC3784</pre>
```
=> Fix error in Request ID regex

wafw00f/main.py
This is needed for HTTP Basic Authentication for example, which will get detected as a generic WAF otherwise.
Before this commit the “normal” requests were made with the `Authorization` header intact, whereas the generic request would remove the `Authorization` header and result in a 403 Forbidden.
No, I just noticed it myself.
No.
No.
There is a quicker way to merge the dictionaries, but it is for Python 3.5 and above, so I hope this is okay.
=> Add custom headers (except for user agent) for generic detection

wafw00f/main.py
I think global rq is not a good practice. And it blocks to use WAFW00F as a library. This way we can use as a library.
For example;
```python
from wafw00f.main import WAFW00F
attacker = WAFW00F(target="http://example.com")
waf = attacker.identwaf()
```
=> remove global rq

wafw00f/plugins/cloudprotector.py, wafw00f/wafprio.py
This SaaS WAF is the official cloud protection by Rhode & Schwarz,
it probably use a "DenyALL" engine, so i set a priority just before
'DenyALL (Rohde & Schwarz CyberSecurity)',
=> Detect Rhode & Schwarz Cloud Protector

wafw00f/main.py
`attacker = WafW00F(None)` used to be necessary when `main.py` was first created:
https://github.com/EnableSecurity/wafw00f/blob/1275ba1f36135bc8abdcfa857f5bca39ff1d987d/wafw00f/main.py#L778-L782
`attacker = WafW00F(None)` was later changed to `WafW00F(None)` in d6cf82826244d93d30f3c9ce1aa3c758f6e1a322.
https://github.com/EnableSecurity/wafw00f/blob/d6cf82826244d93d30f3c9ce1aa3c758f6e1a322/wafw00f/main.py#L348-L350
As best I can tell this line is unnecessary.
This line causes issues when wafw00f is piped to another tool.
Note the invalid URL error.
```
$ wafw00f -l | head -n 30
ERROR:wafw00f:Something went wrong Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
______
/      \
(  Woof! )
\  ____/                      )
,,                           ) (_
.-. - …
```
=> Remove unnecessary WAFWOOF object initialisation when listing WAFs

wafw00f/plugins/f5bigipasm.py
Some people use custom page on BIG-IP ASM, then the original schemes will not compare.
BIG-IP ASM system sets cookies begin with TS, the number of subsequent digits varies with the version, so I append the schema2 pattern.
ref:  https://support.f5.com/csp/article/K6850#main
NO
NO
NO
NO
=> update f5bigipasm detect pattern

wafw00f/lib/asciiarts.py, wafw00f/main.py
ANSI colors in the output interfere with the automatic processing of results. I've added a CLI option to disable colors (`--no-colors`).
This required me to also make changes to how the ANSI colors are stored. They were originally directly imported from `asciiarts.py`, but this makes controlling these values more difficult. I've therefore added a `Color` dataclass and added a `disable()` classmethod. In order to preserve the rest of the functionality, and maintain the brevity of using single letters for colors, I've added an `unpack()` function that can be used to declare colors where needed locally.
No.
No.
Yes, this PR includes the `--no-colors` or `-C` CLI argument.
Thank you for developing `wafw00f`. I use it frequently during security assessments.
=> Added an option to disable colors from output. 

README.md, wafw00f/plugins/envoy.py, wafw00f/wafprio.py
No
No
No
I've added the plugin but I have just seen the header server envoy, so I would improve that because my first scan doesn't seem to detect it...
I've followed the documentation here : https://github.com/EnableSecurity/wafw00f/wiki/Writing-New-WAF-Checks
=> adding Envoy Reverse proxy to plugins

setup.py
"scripts" is an old way of doing it, entry_points is the way to go. See:
https://stackoverflow.com/questions/18787036/difference-between-entry-points-console-scripts-and-scripts-in-setup-py
This pull request fixes the following error:
```
python3.12 -m gpep517 install-wheel --destdir=/var/tmp/portage/net-analyzer/wafw00f-2.3.0/work/wafw00f-2.3.0-python3_12/install --interpreter=/usr/bin/python3.12 --prefix=/usr --optimize=all /var/tmp/portage/net-analyzer/wafw00f-2.3.0/work/wafw00f-2.3.0-python3_12/wheel/wafw00f-2.3.0-py3-none-any.whl
2024-12-24 09:18:06,380 gpep517 INFO Installing /var/tmp/portage/net-analyzer/wafw00f-2.3.0/work/wafw00f-2.3.0-python3_12/wheel/wafw00f-2.3.0-py3-none-any.whl into /var/tmp/portage/net-analyzer/wafw00f-2.3.0/work/wafw00f-2.3.0-python3_12/install
Traceback …
```
=> setup.py installs wafw00f binary twice

README.md, wafw00f/plugins/baffinbay.py, wafw00f/wafprio.py
Detected by header in response.
Tested in Docker on macOS 15.3.1 on Apple Silicon
=> Add detection support for Baffin Bay

wafw00f/plugins/f5bigipasm.py
The improvement for the module `f5bigipasm.py` introduced in https://github.com/EnableSecurity/wafw00f/pull/229 broke its functionality:
```
Traceback (most recent call last):
  File "/usr/local/bin/wafw00f", line 33, in <module>
    sys.exit(load_entry_point('wafw00f==2.3.1', 'console_scripts', 'wafw00f')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wafw00f-2.3.1-py3.11.egg/wafw00f/main.py", line 502, in main
    waf, xurl = attacker.identwaf(options.findall)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/wafw00f-2.3.1-py3.11.egg/wafw00f/main.py", line 285, in identwaf
    if self.wafdetections[wafvendor](self):
      …
```
=> Fixed type missmatch introduced in PR 229
