EnableSecurity/wafw00f

- setup.py
- wafw00f/__init__.py
upload 0.9.3 to PYPI: https://pypi.python.org/pypi/wafw00f
```
pip install wafw00f
```
> update version to 0.9.3

- wafw00f/main.py
> init extraheaders

- wafw00f/main.py
File "/venv/lib/python3.5/site-packages/wafw00f/main.py", line 174, in genericdetect
cleanresponse, _tmp = r
'NoneType' object is not iterable
I centralized the response checking to avoid this in the future.
> Unchecked response for self.cleanhtmlencoded() caused an unexpected error

- setup.py
https://github.com/pypa/sampleproject/blob/master/setup.py
> Add classifiers and Keywords per PyPi sample

- wafw00f/plugins/naxsi.py
Hi, 
Pull request for identification of Naxsi Waf.
Please revert for any concerns,
Regards,
Syed
> Adding identification for Naxsi

- wafw00f/plugins/blackdos.py
Hello,
Adding  plugin for BlackDos.
Let me know if any issues or concern.
Thanks,
Puja
> Adding plugin BlackDos

- wafw00f/plugins/wallarm.py
Hello,
Adding plugin Wallarm.
Let me know if any concerns.
Regards,
Puja
> Adding plugin Wallarm

- wafw00f/plugins/comodo.py
Hello, 
Added plugin Comodo. 
Let me know in case of any concerns.
Regards,
Puja
> Adding plugin Comodo

- wafw00f/plugins/fortiweb.py
Hello, 
Addded plugin for Fortiweb.
Let me know if any concerns.
Regards,
Puja
> Added plugin Fortiweb

- wafw00f/plugins/radware.py
Hi,
Pull request for adding plugin Radware. 
Cheers,
Syed
> Adding plugin for Radware

- wafw00f/plugins/airlock.py
Hi
The manufacturer of Airlock is Ergon: https://airlock.com/en/home/
Cheers,
Emanuel
> The manufacturer of Airlock is Ergon

- wafw00f/plugins/aspnetgen.py
- wafw00f/wafprio.py
More fingerprints for ASP.NET, this time with Debug Mode enabled. :)
> More fingerprints for ASP.NET Generic WAF

- setup.py
> Fix setup.py Homepage and Description

- setup.py
- wafw00f/main.py
> Adding fix for #79

- wafw00f/lib/evillib.py
- wafw00f/main.py
issue #90 
copy
Found this issue when looping over multiple hosts which required generic detection.
> fixed issue #90 generic firewall detection failure

- wafw00f/plugins/frontdoor.py
- wafw00f/wafprio.py
- This PR adds support for Azure Front Door
- Reference can be found here: https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/frontdoor/front-door-http-headers-protocol.md
> Add Azure Front Door Support

- docs/wafw00f.8
- setup.py
- wafw00f/lib/asciiarts.py
- wafw00f/main.py
#93 
Adds `-i/--input` and `-o/--output`.
This is a WIP PR.
> WIP: Adding I/O Feature to wafw00f

- wafw00f/main.py
> Added updates to ease stdout response

- wafw00f/lib/evillib.py
- wafw00f/main.py
> Minor Code Refactor

- wafw00f/plugins/qcloud.py
a plugin for Qcloud Web Application Firewall
just add a plugin
> add qcloud.py

- wafw00f/plugins/wpmudev.py
- wafw00f/wafprio.py
> Add wpmudev WAF support

- wafw00f/main.py
> Pull request for dev

- wafw00f/plugins/anquanbao.py
- wafw00f/plugins/baidu.py
- wafw00f/plugins/safedog.py
Some of the plugins were missing signatures. Feel free to rid of the comments. More soon, team.
> added some extra signatures

- wafw00f/main.py
> Fix AttributeErrors

- wafw00f/main.py
no
no
yes : --format
In some case it is useful to force the format on stdout (--output=-).
This patch add --format=csv|json|text. This patch doesn't modify
anything in the current Wafw00f behavior, it ensure CLI compatibility.
rules are:
- if recognize file extension (csv, json), format is ingnored
- if do not reconize extension and format is not set, default format is text
- if do not reconize extension and format set, sue the format.
> Force output format

- wafw00f/plugins/cloudprotector.py
> New fingerprint based on url + updated regex

- wafw00f/plugins/shieldon.py
Adds a new plugin for [Shieldon Firewall](https://shieldon.io/en) Web Application Firewall for PHP. Fairly new (2 years old). Not very popular (a handful of sites in the wild). Multiple popular PHP frameworks are supported.
Test sites:
* https://terryl.in/
* https://shieldon.io/en
Matches are based on default HTTP headers and default templates:
* https://github.com/terrylinooo/shieldon/blob/2.x/templates/frontend/
> Add Shieldon Firewall

- wafw00f/main.py
#147 ([BUG] AttributeError: 'NoneType' object has no attribute 'headers')
> Fix issue #147 ([BUG] AttributeError: 'NoneType' object has no attribute 'headers')

- wafw00f/main.py
> Fixes nonetype handling #146

- wafw00f/main.py
> Fix AttributeError: 'NoneType' object has no attribute 'status_code' (issue #153)

- wafw00f/plugins/qrator.py
- wafw00f/wafprio.py
> add qrator

- README.md
- wafw00f/wafprio.py
Unfortunately I forgot update readme. Also fixed list
> add qrator to readme and fix list

- Dockerfile
- README.md
No
No
No
This is helpful for people who already use the Docker ecosystem with many tools with different (possible) conflicting dependencies.
> Adding Docker support

- wafw00f/plugins/stackpath.py
> Added StackPath WAF signature updates

- wafw00f/plugins/aliyundun.py
Removed the cookie check because cookies are changing quite frequently from the looks of it.
> Update signatures for aliyundun firewall

- wafw00f/plugins/fortigate.py
- wafw00f/plugins/fortiguard.py
- wafw00f/wafprio.py
> Add FortiGate WAF profile support

- Dockerfile
This should make image ~ 70-90% smaller:
Docker image based on python:3
```
wafw00f                            latest          894e9ebea58f   7 seconds ago    935MB
```
Docker image based on python:3-alpine
```
wafw00f                            latest          1724fc03b927   4 seconds ago   67.1MB
```
> Changed Dockerfile to use python:3-alpine instead of python:3

- wafw00f/plugins/variti.py
- wafw00f/wafprio.py
> Variti waf

- wafw00f/main.py
Closes #178.
Introduces `string` for generating random strings.
None
> added random param support

- .gitignore
- wafw00f/lib/evillib.py
- wafw00f/main.py
> Added trigger URL in response

- README.md
- wafw00f/plugins/azion.py
- wafw00f/wafprio.py
Noup
Noup
Noup
Before fix:
```
$ wafw00f -a https://www.azion.com https://api.azion.com
______
/      \
(  W00f! )
\  ____/
,,    __            404 Hack Not Found
|`-.__   / /                      __     __
/"  _/  /_/                       \ \   / /
*===*    /                          \ \_/ /  405 Not Allowed
/     )__//                           \   /
/|  /     /---`                        403 Forbidden
\\/`   \ |                                 / _ \
`\    /_\\_              502 Bad Gateway  / / \ \  500 Internal Error
`_____``-`                             /_/   \_\
~ WAFW00F : v2.2.0 ~
The Web Application Firewall Fingerprinting Toolkit
[*] Checking https://www.azion.com
[+] Generic Detection results:
[-] No WAF detected by the generic detection …
```
> Fix Azion Edge Firewall detection and product name

- README.md
- wafw00f/plugins/applicationgateway.py
- wafw00f/wafprio.py
No
No
No
Can't be tested like Azure Front Door with a header. Only a content match is possible
Documentation: https://learn.microsoft.com/en-us/entra/identity/app-proxy/application-proxy-application-gateway-waf
> Add support to Azure application Gateway

- CREDITS.txt
- Dockerfile
- README.md
- docs/wafw00f.8
- wafw00f/__init__.py
- wafw00f/lib/asciiarts.py
- wafw00f/lib/evillib.py
- wafw00f/main.py
> new release
adds `-T` and `--timeout` for controlling timeout of requests.
> (feat) wafw00f 2.3.0: new release ready

- README.md
- setup.py
- wafw00f/__init__.py
> (release) minor subrelease: 2.3.1

- README.md
- wafw00f/plugins/siteguard.py
- wafw00f/wafprio.py
No
No
No
They say "It is developed in-house".
> 自社開発製品ですか。
> Webアプリケーションファイアウォール「SiteGuardシリーズ」は、日本企業であるEGセキュアソリューションズが開発する純国産製品です。
https://www.eg-secure.co.jp/siteguard/faq/siteguard-summary
> Fix: incorrect manufacturer

- README.md
- wafw00f/plugins/link11.py
- wafw00f/wafprio.py
https://github.com/EnableSecurity/wafw00f/issues/230
No
No
> Add Link11 WAAP Detection

- README.md
- wafw00f/plugins/panyun360.py
- wafw00f/wafprio.py
> add 360 PanYun WAF detection

- README.md
- wafw00f/__init__.py
> new minor subrelease 2.3.2
